### ISSUE TITLE
问好

### ISSUE THREAD

**Issue by nobodxbodon** [vivaxyblog/vivaxyblog.github.io#10]
你好，在为设想《[基于 git 的去中心化内容收发平台](https://zhuanlan.zhihu.com/p/346258393)》向各位博主征求意见建议、搜集公开的 git 仓库。

有幸从 [独立博客列表](https://github.com/timqian/chinese-independent-blogs) 发现此仓库，添加到了 [此索引](https://gitee.com/zhishi/collection-of-chinese-blogs) ，打算为设想建设原型时作为内容源之一。

欢迎任何建议意见。

**Comment by vivaxy** [comment]
欢迎使用内容，烦请注明出处。

**Comment by nobodxbodon** [comment]
写了个功能简介，借用了部分内容，欢迎意见建议：https://gitee.com/zhishi/collection-of-chinese-blogs/blob/master/%E6%96%87%E6%A1%A3/2021-01-26-%E5%9F%BA%E4%BA%8E%20git%20%E7%9A%84%E5%8D%9A%E5%AE%A2%E8%81%9A%E5%90%88%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%88%E4%B8%80%EF%BC%89%EF%BC%9A%E8%AF%BB%E8%80%85.md

**Comment by nobodxbodon** [comment]
已过一月有余，报告一下进展，已有十六位博主同意将博文 git 仓库加入内容源，博文一千三百多篇。
现在小结功能需求、做一些简单技术调研，详细进展[在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)，可见统计数据、所有博文目录等。
下面打算在本地预览 md 文件、全文搜索与排序等方向继续调研。
欢迎任何意见建议~
